#!/usr/bin/env php
<?php
/**
 * A cli tool that helps convert json and yaml beetween each other
 */
require('./vendor/autoload.php');
use function Converter\converter;
$options = getopt("i:o:");
if (!isset($options['i']) || !isset($options['o'])) {
    echo 'missing parametrs. usage convert -i input.file -o output.file';
    exit(1);
}
converter($options['i'], $options['o']);
exit(0);
